In [1]:
a = [1, 2, 3, 4, 5]
b = [1, 2, 3, 4, 5]

In [2]:
c = []
for i in range(5):
  c.append(a[i]+b[i])

print(c)

[2, 4, 6, 8, 10]


In [3]:
[sum(x) for x in zip(a,b)]

[2, 4, 6, 8, 10]

In [5]:
%%time 
c = [sum(x) for x in zip(a,b)]

CPU times: user 7 µs, sys: 0 ns, total: 7 µs
Wall time: 10.5 µs


In [6]:
c

[2, 4, 6, 8, 10]

In [7]:
a = list(range(100_000))
b = list(range(100_000))

In [8]:
%%time 
c = [sum(x) for x in zip(a,b)]

CPU times: user 24.1 ms, sys: 4.64 ms, total: 28.7 ms
Wall time: 31 ms


In [ ]:
c

In [10]:
a = list(range(100_000_000))
b = list(range(100_000_000))

In [ ]:
%%time 
c = [sum(x) for x in zip(a,b)]

In [1]:
import numpy as np

In [2]:
A = np.array([1, 2, 3])
A

array([1, 2, 3])

In [3]:
type(A)

numpy.ndarray

In [4]:
A_list = [1, 2 , 3]
type(A_list)

list

In [5]:
A_list+A_list

[1, 2, 3, 1, 2, 3]

In [6]:
A+A

array([2, 4, 6])

In [7]:
A = np.array(list(range(1_000_000)))

In [8]:
%%time
A+A

CPU times: user 1.75 ms, sys: 18.1 ms, total: 19.9 ms
Wall time: 25 ms


array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [9]:
A = np.array([1, 2, 3])
A

array([1, 2, 3])

In [10]:
type(A)

numpy.ndarray

In [11]:
A.dtype

dtype('int64')

In [12]:
A = np.array([1, 2, '3', True])

In [13]:
type(A)

numpy.ndarray

In [14]:
A.dtype

dtype('<U21')

In [15]:
A.tolist()

['1', '2', '3', 'True']

In [16]:
list(A)

['1', '2', '3', 'True']

In [17]:
A = np.array([1, 2, 3, 4, 5, 6])
A

array([1, 2, 3, 4, 5, 6])

In [18]:
A[0]

1

In [19]:
A[0:2]

array([1, 2])

In [20]:
A[::-1]

array([6, 5, 4, 3, 2, 1])

In [21]:
A[0] = 10
A

array([10,  2,  3,  4,  5,  6])

In [22]:
A = np.array([1, 2, 3, 4, 5, 6])
B = A
A[0] = 10

In [23]:
A

array([10,  2,  3,  4,  5,  6])

In [24]:
B

array([10,  2,  3,  4,  5,  6])

In [25]:
A = np.array([1, 2, 3, 4, 5, 6])
B = A.copy()
A[0] = 10

In [26]:
A

array([10,  2,  3,  4,  5,  6])

In [27]:
B

array([1, 2, 3, 4, 5, 6])

In [28]:
A = np.array([1, 2, 3, 4, 5, 6])
B = A
C = A.copy()

In [29]:
id(A)

140092012248880

In [30]:
id(B)

140092012248880

In [32]:
id(C)

140092012248496

In [33]:
id(A) == id(B)

True

In [34]:
id(A) == id(C)

False

In [35]:
A = np.array([1, 2, 3, 4, 5, 6])

In [36]:
A[[4, 4, 4, 4, 4, 4]]

array([5, 5, 5, 5, 5, 5])

In [37]:
A[[4, 4, 4]]

array([5, 5, 5])

In [38]:
A[[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]]

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [39]:
A[[True, True, False, True, False, False]]

array([1, 2, 4])

In [40]:
A = np.array([1, 2, 3, 4, 5, 6])

In [41]:
1 in A

True

In [42]:
8 in A

False

In [43]:
A = np.array([1, 2, 3])
B = np.array([1, 1, 1])

In [44]:
(A==1).any()

True

In [45]:
(B==2).any()

False

In [46]:
(A==1).all()

False

In [47]:
(B==1).all()

True

In [48]:
A = np.array([1, 1, 3, 1, 5, 3])
unique, counts = np.unique(A, return_counts=True)
for i in range(len(unique)):
  print(f'значение {unique[i]} встречается {counts[i]} раз')

значение 1 встречается 3 раз
значение 3 встречается 2 раз
значение 5 встречается 1 раз


In [49]:
A = np.array([0]*10)

In [50]:
A = np.zeros((10))
A

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [51]:
B = np.ones((5))
B

array([1., 1., 1., 1., 1.])

In [52]:
A1 = np.zeros_like(B)
A1

array([0., 0., 0., 0., 0.])

In [53]:
B1 = np.ones_like(A)
B1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [54]:
np.full((10,), 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [55]:
A = np.ones((3))
B = A.astype('str')

In [56]:
A

array([1., 1., 1.])

In [57]:
B

array(['1.0', '1.0', '1.0'], dtype='<U32')

In [58]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [59]:
list(range(5, 10))

[5, 6, 7, 8, 9]

In [60]:
list(range(5, 10, 2))

[5, 7, 9]

In [61]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [63]:
np.arange(5, 10, 2)

array([5, 7, 9])

In [64]:
np.arange(5, 10, 0.5)

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [65]:
np.arange(0.1, 1, 0.2)

array([0.1, 0.3, 0.5, 0.7, 0.9])

In [66]:
np.arange(0, np.pi, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1])

In [67]:
np.pi

3.141592653589793

In [68]:
np.random.rand(10)

array([0.45919823, 0.5553602 , 0.54420954, 0.1458833 , 0.47313979,
       0.77579453, 0.97415942, 0.55891421, 0.05041931, 0.04250962])

In [69]:
np.random.randn(10)

array([ 1.3411217 , -1.36230033,  1.31796038,  1.28212463, -1.14974533,
       -0.09205121,  0.15259477,  0.94686602, -0.85127801,  0.62398113])