In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [3]:
A

array([[1, 2],
       [3, 4]])

In [4]:
B

array([[5, 6],
       [7, 8]])

In [5]:
np.hstack([A, B])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [6]:
np.vstack([A, B])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [7]:
A = np.array([[1], [2], [3], [4]])
B = np.array([[5], [6], [7], [8]])

In [8]:
A

array([[1],
       [2],
       [3],
       [4]])

In [9]:
B

array([[5],
       [6],
       [7],
       [8]])

In [10]:
np.hstack([A, B])

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [11]:
np.vstack([A, B])

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [12]:
A = np.array([1, 2, 3, 4])
B = np.array([5, 6, 7, 8])

In [13]:
np.hstack([A, B])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
np.vstack([A, B])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
A = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
A

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
np.hsplit(A, 2)

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]

In [18]:
np.hsplit(A, 3)

ValueError: ignored

In [19]:
np.hsplit(A, 4)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

In [20]:
np.vsplit(A, 2)

ValueError: ignored

In [21]:
A.shape

(8,)

In [22]:
A = A.reshape(8,1)
A

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [24]:
np.vsplit(A, 2)

[array([[1],
        [2],
        [3],
        [4]]), array([[5],
        [6],
        [7],
        [8]])]

In [25]:
A = np.array([[1, 2], [3, 4], [5,6], [7,8]])
A

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [26]:
np.hsplit(A, 2)

[array([[1],
        [3],
        [5],
        [7]]), array([[2],
        [4],
        [6],
        [8]])]

In [27]:
np.vsplit(A, 2)

[array([[1, 2],
        [3, 4]]), array([[5, 6],
        [7, 8]])]

In [28]:
A_list = [1, 2, 3, 4]
A_np = np.array([1, 2, 3, 4])

In [29]:
A_list * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [30]:
A_np * 2

array([2, 4, 6, 8])

In [31]:
[i*2 for i in A_list]

[2, 4, 6, 8]

In [32]:
A = np.array([1, 2, 3, 4])

In [33]:
- A

array([-1, -2, -3, -4])

In [34]:
A+1

array([2, 3, 4, 5])

In [35]:
1+A

array([2, 3, 4, 5])

In [36]:
A-1

array([0, 1, 2, 3])

In [37]:
1-A

array([ 0, -1, -2, -3])

In [38]:
A*2

array([2, 4, 6, 8])

In [39]:
2*A

array([2, 4, 6, 8])

In [40]:
A/2

array([0.5, 1. , 1.5, 2. ])

In [41]:
8/A

array([8.        , 4.        , 2.66666667, 2.        ])

In [42]:
A//2

array([0, 1, 1, 2])

In [43]:
8//A

array([8, 4, 2, 2])

In [44]:
A%2

array([1, 0, 1, 0])

In [45]:
A**2

array([ 1,  4,  9, 16])

In [46]:
2**A

array([ 2,  4,  8, 16])

In [47]:
A = np.array([1, 2, 3, 4])
B = np.array([5, 6, 7, 8])

In [48]:
A+B

array([ 6,  8, 10, 12])

In [49]:
A-B

array([-4, -4, -4, -4])

In [50]:
A*B

array([ 5, 12, 21, 32])

In [51]:
A/B

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [52]:
A//B

array([0, 0, 0, 0])

In [53]:
A%B

array([1, 2, 3, 4])

In [54]:
A**B

array([    1,    64,  2187, 65536])

In [55]:
C = np.array([3,4])
A+C

ValueError: ignored

In [56]:
A = np.arange(0, 10, 2)
B = np.arange(9, 0, -2)

In [57]:
A

array([0, 2, 4, 6, 8])

In [58]:
B

array([9, 7, 5, 3, 1])

In [59]:
A+B

array([9, 9, 9, 9, 9])