In [1]:
import numpy as np

In [2]:
A = np.array([1, 2, 3, 4, 5, 6])

In [3]:
A.sum()

21

In [4]:
A.mean()

3.5

In [5]:
A.max()

6

In [6]:
A.min()

1

In [7]:
A = A.reshape((3, 2))
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
A.sum()

21

In [9]:
A.mean()

3.5

In [10]:
A.max()

6

In [11]:
A.min()

1

In [12]:
A.sum(axis=0)

array([ 9, 12])

In [13]:
A.sum(axis=1)

array([ 3,  7, 11])

In [14]:
A.max(axis=1)

array([2, 4, 6])

In [15]:
A.min(axis=0)

array([1, 2])

In [16]:
np.random.seed(123)
A = np.random.randint(1, 100, 100)
A = A.reshape(5, 20)
A

array([[67, 93, 99, 18, 84, 58, 87, 98, 97, 48, 74, 33, 47, 97, 26, 84,
        79, 37, 97, 81],
       [69, 50, 56, 68,  3, 85, 40, 67, 85, 48, 62, 49,  8, 93, 53, 98,
        86, 95, 28, 35],
       [98, 77, 41,  4, 70, 65, 76, 35, 59, 11, 23, 78, 19, 16, 28, 31,
        53, 71, 27, 81],
       [ 7, 15, 76, 55, 72,  2, 44, 59, 56, 26, 51, 85, 57, 50, 13, 19,
        82,  2, 52, 45],
       [49, 57, 92, 50, 87,  4, 68, 12, 22, 90, 99,  4, 12,  4, 95,  7,
        10, 88, 15, 84]])

In [17]:
A.mean()

53.62

In [18]:
A.mean(axis=0)

array([58. , 58.4, 72.8, 39. , 63.2, 42.8, 63. , 54.2, 63.8, 44.6, 61.8,
       49.8, 28.6, 52. , 43. , 47.8, 62. , 58.6, 43.8, 65.2])

In [19]:
A.min()

2

In [20]:
A.max()

99

In [21]:
np.median(A)

55.5

In [22]:
np.var(A)

920.8156

In [23]:
np.std(A)

30.344943565609082