In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

In [3]:
A + 10

array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18]])

In [4]:
A - 10

array([[-9, -8],
       [-7, -6],
       [-5, -4],
       [-3, -2]])

In [5]:
A ** 2

array([[ 1,  4],
       [ 9, 16],
       [25, 36],
       [49, 64]])

In [6]:
A = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
B = np.array([[10, 20]])

In [7]:
A

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [8]:
B

array([[10, 20]])

In [9]:
A.shape

(4, 2)

In [10]:
B.shape

(1, 2)

In [11]:
A+B

array([[11, 22],
       [13, 24],
       [15, 26],
       [17, 28]])

In [12]:
A-B

array([[ -9, -18],
       [ -7, -16],
       [ -5, -14],
       [ -3, -12]])

In [13]:
A/B

array([[0.1, 0.1],
       [0.3, 0.2],
       [0.5, 0.3],
       [0.7, 0.4]])

In [14]:
A = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
B = np.array([10, 20, 30])
A+B

ValueError: ignored

In [15]:
A = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
B = np.array([[10, 20, 30, 40]])
A+B

ValueError: ignored

In [16]:
A = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
B = np.arange(10, 81, 10)
B = np.reshape(B, (4,2))

In [17]:
A

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [18]:
B

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [19]:
A+B

array([[11, 22],
       [33, 44],
       [55, 66],
       [77, 88]])

In [20]:
A-B

array([[ -9, -18],
       [-27, -36],
       [-45, -54],
       [-63, -72]])

In [21]:
B-A

array([[ 9, 18],
       [27, 36],
       [45, 54],
       [63, 72]])

In [22]:
A*B

array([[ 10,  40],
       [ 90, 160],
       [250, 360],
       [490, 640]])

In [23]:
A/B

array([[0.1, 0.1],
       [0.1, 0.1],
       [0.1, 0.1],
       [0.1, 0.1]])

In [24]:
B/A

array([[10., 10.],
       [10., 10.],
       [10., 10.],
       [10., 10.]])

In [25]:
A//B

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [26]:
A%B

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [27]:
B**A

array([[              10,              400],
       [           27000,          2560000],
       [       312500000,      46656000000],
       [   8235430000000, 1677721600000000]])

In [28]:
C = np.array([[1, 2, 3], [4, 5, 6]])
A+C

ValueError: ignored

In [29]:
A

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [30]:
C = np.array([3, 4])
A+C

array([[ 4,  6],
       [ 6,  8],
       [ 8, 10],
       [10, 12]])

In [31]:
C

array([3, 4])

In [32]:
A+100

array([[101, 102],
       [103, 104],
       [105, 106],
       [107, 108]])

In [33]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.ones((3, 3))

In [34]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
B*5 - A//2

array([[5., 4., 4.],
       [3., 3., 2.],
       [2., 1., 1.]])

In [37]:
B *= 5
B -= A//2
B

array([[5., 4., 4.],
       [3., 3., 2.],
       [2., 1., 1.]])

In [38]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
A*I

array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 9.]])

In [40]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])