In [1]:
import numpy as np

In [2]:
A = np.arange(1, 5)
A = np.reshape(A, (2,2))
A

array([[1, 2],
       [3, 4]])

In [3]:
I = np.eye(2)*2
I

array([[2., 0.],
       [0., 2.]])

In [4]:
A*I

array([[2., 0.],
       [0., 8.]])

In [5]:
np.dot(A, I)

array([[2., 4.],
       [6., 8.]])

In [6]:
A = np.arange(1, 5)
A = np.reshape(A, (1,4))
A

array([[1, 2, 3, 4]])

In [7]:
A.T

array([[1],
       [2],
       [3],
       [4]])

In [8]:
A*A.T

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [9]:
np.dot(A, A.T)

array([[30]])

In [10]:
A = 2
B = 3

np.dot(A, B)

6

In [11]:
A = np.array([2, 3, 4])
B = 3

np.dot(A, B)

array([ 6,  9, 12])

In [12]:
A = np.array([2, 3, 4])
B = np.array([-2, 1, -1])

np.dot(A, B)

-5

In [13]:
A = np.array([[2, 3, 4], [5, 6, 7]])
B = 2

np.dot(A, B)

array([[ 4,  6,  8],
       [10, 12, 14]])

In [14]:
A = np.array([[2, 3, 4], [5, 6, 7]])
B = np.array([-2, 1, -1])

np.dot(A, B)

array([ -5, -11])

In [15]:
X = np.array([1, 3, 4, 5, 7])
X = np.reshape(X, (5,1))
X

array([[1],
       [3],
       [4],
       [5],
       [7]])

In [16]:
Y = np.array([6, 16, 21, 26, 36])
Y = np.reshape(Y, (5,1))
Y

array([[ 6],
       [16],
       [21],
       [26],
       [36]])

In [17]:
E = np.ones((5, 1))
E

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [18]:
X = np.hstack([E, X])
X

array([[1., 1.],
       [1., 3.],
       [1., 4.],
       [1., 5.],
       [1., 7.]])

In [19]:
X.T

array([[1., 1., 1., 1., 1.],
       [1., 3., 4., 5., 7.]])

In [20]:
A = np.dot(X.T, X)
A

array([[  5.,  20.],
       [ 20., 100.]])

In [21]:
np.linalg.det(A)

99.99999999999996

In [22]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 1.  , -0.2 ],
       [-0.2 ,  0.05]])

In [23]:
B = np.dot(X.T, Y)
B

array([[105.],
       [520.]])

In [24]:
w = np.dot(A_inv, B)
w

array([[1.],
       [5.]])

In [25]:
X

array([[1., 1.],
       [1., 3.],
       [1., 4.],
       [1., 5.],
       [1., 7.]])

In [26]:
w

array([[1.],
       [5.]])

In [27]:
np.dot(X, w)

array([[ 6.],
       [16.],
       [21.],
       [26.],
       [36.]])

In [28]:
Y

array([[ 6],
       [16],
       [21],
       [26],
       [36]])

In [29]:
np.dot(X, w) == Y

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True]])